# Secrets pour Streamlit Cloud
# Ce fichier ne sera pas poussé sur GitHub, mais vous devrez configurer 
# les mêmes secrets dans l'interface Streamlit Cloud

[openai]
api_key = "" # Laissez vide ici, à remplir dans Streamlit Cloud
